### ISSUE TITLE
Why fuse-overlayfs

### ISSUE THREAD

**Issue by phlogistonjohn** [ceph/ceph-devstack#1]
I am curious about the storage.conf embedded in the sources and have a two part question: why does the project overirde the default storage settings and why does it use fuse-overlayfs.

For context, I think recent versions of podman with linux are supposed to benefit from kernel overlayfs even when rootless. See: https://www.redhat.com/sysadmin/podman-rootless-overlay  for example.

So I'm wondering if you've hit an issue where kernel overlayfs wasn't working?

**Comment by zmc** [comment]
Good question! The short answer is: I was unaware native overlay was working! I'd been using [podman's rootless tutorial](https://github.com/containers/podman/blob/main/docs/tutorials/rootless_tutorial.md) and [this blog post](https://www.redhat.com/sysadmin/podman-inside-container) as guides, and apparently neither have been updated with that information.

I'm about to push changes to `main` that will use native overlay where available, and I'm updating our CentOS 9 image so that it has a new enough kernel.

Thanks!
